apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-backup-account
  namespace: nais
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: db-backup-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - get
- apiGroups:
  - "sql.cnrm.cloud.google.com"
  resources:
  - sqldatabases
  - sqlinstances
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: db-backup-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: db-backup-role
subjects:
- kind: ServiceAccount
  name: db-backup-account
  namespace: nais
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: db-backup
  namespace: nais
spec:
  schedule: "* 04 * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          name: db-backup
          annotations:
            prometheus.io/scrape: 'false'
          labels:
            app: db-backup
        spec:
          serviceAccountName: db-backup-account
          imagePullSecrets:
            - name: gpr-credentials
          containers:
          - name: db-backup
            image: navikt/db-backup:0.3
            imagePullPolicy: Always
            resources:
              requests:
                cpu: "0.2"
                memory: 256Mi
              limits:
                cpu: "2"
                memory: 512Mi
            volumeMounts:
            - mountPath: /credentials
              name: db-backup-secret
          restartPolicy: OnFailure
          serviceAccountName: db-backup-account
          volumes:
          - name: db-backup-secret
            secret:
              secretName: db-backup-secret
